/**
 * Every image in this project is described declaratively: the *final* path it
 * will live at in `public/`, the alt text, the exact pixel size to generate,
 * and the AI prompt used to produce it.
 *
 * Until the real file exists on disk, `<Media>` renders a branded placeholder.
 * Drop the generated file at `src` and it takes over automatically — no code
 * change required. See IMAGE-PROMPTS.md (generated by `pnpm images:manifest`).
 */
export type ImageAsset = {
  /** Path under public/, e.g. "/images/products/aurora-kurti.jpg" */
  src: string;
  alt: string;
  /** Intrinsic size to generate at. Also used to reserve layout space. */
  width: number;
  height: number;
  /**
   * Prompt to feed an image model. For banners this is what gets generated;
   * for products it doubles as the shoot brief when real photography replaces
   * the demo stand-in.
   */
  prompt: string;
  /**
   * Where the demo stand-in came from, e.g. "dummyjson:83". Present only on
   * assets that ship with a placeholder photo — every one of these must be
   * replaced with the client's own product photography before launch.
   */
  demoSource?: string;
};

export type CategorySlug =
  | "fashion"
  | "gadgets"
  | "home-essentials"
  | "beauty"
  | "fragrances"
  | "lifestyle"
  | "sports"
  | "watches-bags";

export type Subcategory = {
  slug: string;
  /**
   * Must match the `subcategory` string on the products that belong to it —
   * that name is the join between the two, and `assertSubcategories()` in
   * data/index.ts fails the build if they ever drift apart.
   */
  name: string;
};

export type Category = {
  slug: CategorySlug;
  name: string;
  /** Short label for the compact circular scroller under the header. */
  shortName: string;
  /**
   * One-line description. Not rendered on the homepage any more — the grid
   * tiles show subcategory links instead, which are more useful — but kept
   * because the category page needs it for its intro and meta description.
   */
  blurb: string;
  itemCount: number;
  /** Tailwind class pair used for the placeholder + chip tint. */
  tint: string;
  image: ImageAsset;
  subcategories: Subcategory[];
};

export type ColorOption = {
  name: string;
  hex: string;
  /** A colour can sell out on its own. Defaults to true when omitted. */
  inStock?: boolean;
};

/**
 * How the size values should be read. Apparel is lettered (S/M/L), footwear is
 * numeric EU, and `onesize` is for things that technically have a size but only
 * one of it — it renders as a note rather than a picker.
 */
export type SizeSystem = "apparel" | "footwear" | "onesize";

export type SizeOption = {
  /** Shown on the chip: "M", "41". */
  value: string;
  /** Spelled out for screen readers and tooltips: "Medium", "EU 41". */
  label: string;
  inStock: boolean;
};

export type SizeGroup = {
  system: SizeSystem;
  options: SizeOption[];
  /** Optional link target for a size chart, when one exists. */
  guideNote?: string;
};

/**
 * A chosen combination. Products may have colour, size, both or neither, so
 * both fields are optional — but whatever the product offers must be picked
 * before it can be added to the cart.
 */
export type Variant = {
  colour?: string;
  size?: string;
  /**
   * Carried alongside the size purely so a cart row can render "EU 42" rather
   * than a naked "42". Deliberately excluded from `variantLineId` — it is a
   * presentation detail, not part of the variant's identity.
   */
  sizeSystem?: SizeSystem;
};

export type ProductBadge = "new" | "bestseller" | "limited" | "restock";

export type Product = {
  id: string;
  slug: string;
  title: string;
  brand: string;
  category: CategorySlug;
  subcategory: string;
  /**
   * Real per-product copy. Optional: until the backend supplies it,
   * `productDescription()` falls back to a category template.
   */
  description?: string;
  /** Current selling price in BDT. */
  price: number;
  /** Original price, struck through. Omit when there is no discount. */
  compareAt?: number;
  rating: number;
  reviewCount: number;
  sold: number;
  stock: number;
  badge?: ProductBadge;
  colors?: ColorOption[];
  sizes?: SizeGroup;
  freeDelivery: boolean;
  /** Flash-sale members carry a deeper price plus a claimed-stock percentage. */
  flash?: { price: number; claimedPercent: number };
  image: ImageAsset;
  tags: string[];
};

/**
 * Whether the artwork itself is pale or dark. It drives the scrim, the text
 * colour and the carousel controls together, so they can never drift apart —
 * a light photo gets ink copy on a white scrim, a dark photo gets white copy
 * on a black one.
 */
export type BannerTone = "light" | "dark" | "none";

export type Banner = {
  id: string;
  eyebrow?: string;
  title: string;
  subtitle: string;
  cta: string;
  href: string;
  tone: BannerTone;
  /** Portrait-ish crop for phones. */
  imageMobile: ImageAsset;
  /** Wide crop for tablet and desktop. */
  imageDesktop: ImageAsset;
};

export type PromoTile = {
  id: string;
  title: string;
  subtitle: string;
  cta: string;
  href: string;
  tone: BannerTone;
  image: ImageAsset;
};

export type Review = {
  id: string;
  name: string;
  location: string;
  rating: number;
  date: string;
  body: string;
  productBought: string;
  verified: boolean;
  /** No avatar field by design — see the note in reviews.ts. */
};
